# render.yaml - Blueprint para el Pasaporte Digital

services:
  # 1. Servicio de la Base de Datos PostgreSQL
  - type: psql
    name: pasaporte-db
    plan: free # Usa el plan gratuito de Render
    pSQLVersion: "15"

  # 2. Servicio del Backend (Node.js)
  - type: web
    name: pasaporte-backend
    plan: free
    runtime: docker
    dockerfilePath: ./backend/Dockerfile # Ruta al Dockerfile del backend
    dockerContext: ./backend          # Carpeta del backend
    envVars:
      - key: DB_HOST
        fromService:
          type: psql
          name: pasaporte-db
          property: host
      - key: DB_USER
        fromService:
          type: psql
          name: pasaporte-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: psql
          name: pasaporte-db
          property: password
      - key: DB_DATABASE
        fromService:
          type: psql
          name: pasaporte-db
          property: database
      - key: JWT_SECRET
        generateValue: true # Render generará un secreto seguro automáticamente

  # 3. Servicio del Frontend (React + Nginx)
  - type: web
    name: pasaporte-frontend
    plan: free
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile # Ruta al Dockerfile del frontend
    dockerContext: ./frontend          # Carpeta del frontend
    # Reglas de reescritura para que React Router funcione
    routes:
      - type: rewrite
        source: /*
        destination: /index.html